# Generated by Django 6.0.1 on 2026-03-16 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_ticket_unique_ticket_per_seat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
